### PR TITLE
Fix issue with Linux Automate profile dependencies

### LINKED ISSUE #117: [scaffolding-chef-inspec] Linux scaffolding errors when attempting pull a dependency from Automate
Tested pulling a profile from Automate this morning for Linux and hit an issue with it parsing the values using `jq`. We have updated the Windows scaffolding to not do this so Linux should have the same behavior. For reference https://github.com/chef/effortless/pull/84

### PR DESCRIPTION
**Pull request by TheLunaticScripter**
Signed-off-by: John Snow <thelunaticscripter@outlook.com>

Fix #117 
When attempting to pull a profile dependency from Automate there was a parsing error with jq. This change brings the scaffolding in line with the update made to Windows scaffolding and provides an API for users to put in their Automate credentials.

### CODE REVIEW

File: scaffolding-chef-inspec/tests/linux/user-a2-profile-dep/controls/example.rb [hunk 1]
```diff
@@ -0,0 +1,8 @@
+# encoding: utf-8
+# copyright: 2018, The Authors
```
Comment (echohack) [inline scaffolding-chef-inspec/tests/linux/user-a2-profile-dep/controls/example.rb]: Please remove these two boilerplate comments

File: scaffolding-chef-inspec/tests/linux/user-a2-profile-dep/habitat/plan.sh [hunk 2]
```diff
@@ -0,0 +1,11 @@
+pkg_name=effortless-a2-profile-test
+pkg_version=0.1.0
```
Comment (echohack) [inline scaffolding-chef-inspec/tests/linux/user-a2-profile-dep/habitat/plan.sh]: Please make this version 1.0.0

File: scaffolding-chef-inspec/tests/linux/user-a2-profile-dep/habitat/plan.sh [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+pkg_origin=chef
+pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
+pkg_license=("Apache-2.0")
+pkg_description="The Audit Baseline InSpec Profile"
+pkg_upstream_url="http://chef.io"
```
Comment (echohack) [inline scaffolding-chef-inspec/tests/linux/user-a2-profile-dep/habitat/plan.sh]: Please remove all metadata from the test package

`pkg_maintainer`
`pkg_license`
`pkg_description`
`pkg_upstream_url`

Removing this helps focus the test, and makes it more readable and understandable for what is under test.

File: scaffolding-chef-inspec/tests/linux/user-a2-profile-dep/inspec.yml [hunk 4]
```diff
@@ -0,0 +1,12 @@
+name: effortless-a2-profile-test
+title: Effortless Automate CIS profile Test
+maintainer: humans@habitat.sh
+copyright: Chef Software Inc.
+copyright_email: humans@habitat.sh
+license: Apache-2.0
+summary: Effortless Automate CIS profile Test
+version: 0.1.0
```
Comment (echohack) [inline scaffolding-chef-inspec/tests/linux/user-a2-profile-dep/inspec.yml]: Please remove all metadata from this file

`maintainer`
`copyright`
`copyright_email`
`license`
`summary`


Please make the version `1.0.0`
